version: '3'
services:
  local-mysql:
    restart: always
    container_name: local-mysql
    image: bitnami/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
  local-adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080   
  todo-app:
    restart: on-failure
    image: ceridian
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
      MYSQL_HOST: local-mysql
    depends_on:
      - local-mysql